# **1주차 복습과제**
- 1주차 복습과제는 **넘파이/판다스 연습문제**입니다.
- 코드 작성하시고, 출력 결과까지 나오도록 실행 부탁드립니다.
  - 제출 시 파일명 본인 이름으로 변경해 주세요. ex) Week1_복습과제_OOO
- 교재에서 다루지 않은 메소드도 다수 포함되어 있지만 구글링이나 챗지피티 등을 활용해서라도 풀어주세요! 한 번씩 사용해 보면 좋을 것 같아 어려워도 문제에 포함했습니다 🤗

## **넘파이**

### 1. Import the numpy package under the name `np`.

In [2]:
import numpy as np

### 2. Print the numpy version and the configuration.

(hint: `np.__version__`, `np.show_config`)

In [2]:
print(np.__version__)
print(np.show_config)

1.24.3
<function show at 0x11582cfe0>

### 3. Create a null vector of size 10.

#### ✅ 출력 예시


```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```

In [3]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

### 4. Create a null vector of size 10 but the fifth value which is 1.

#### ✅출력 예시


```
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
```

In [4]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

### 5. Create a vector with values ranging from 10 to 49.

#### ✅출력 예시


```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
```

In [7]:
array = np.arange(start=10,stop=50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

### 6. Reverse a vector (first element becomes last).

#### ✅출력 예시


```
[9 8 7 6 5 4 3 2 1 0]
```

In [12]:
array = np.arange(10)
reverse_array = np.flip(array)
print(reverse_array)

[9 8 7 6 5 4 3 2 1 0]

### 7. Create a 3x3 matrix with values ranging from 0 to 8.

#### ✅출력 예시


```
[[0 1 2]
 [3 4 5]
 [6 7 8]]
```

In [14]:
array = np.arange(9).reshape((3,3))
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

### 8. Find indices of non-zero elements from [1,2,0,0,4,0].

#### ✅출력 예시


```
(array([0, 1, 4]),)
```

In [23]:
lst = [1,2,0,0,4,0]
array = np.array(lst)
non_zero_indices = np.nonzero(array)
print(non_zero_indices)

(array([0, 1, 4]),)

### 9. Create a 3x3 identity matrix.

(hint: `np.eye`)

#### ✅출력 예시


```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [22]:
array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

### 10. Create a 3x3x3 array with random values.

#### ✅출력 예시


```
[[[0.30742852 0.26458726 0.85474383]
  [0.80234531 0.76268902 0.91286677]
  [0.8804109  0.51011378 0.82103555]]

 [[0.403753   0.83120234 0.15202655]
  [0.75782685 0.0732058  0.48148689]
  [0.2089428  0.44968622 0.88134184]]

 [[0.52251191 0.10738374 0.86279648]
  [0.26203911 0.42157754 0.68856833]
  [0.58133626 0.31059127 0.71354172]]]
```

In [26]:
array = np.random.rand(3,3,3)
print(array)

[[[0.25727451 0.05601064 0.03483417]
  [0.55571248 0.47288089 0.9252687 ]
  [0.067008   0.55880114 0.06169232]]

 [[0.44963594 0.5155719  0.76118805]
  [0.41051074 0.31749335 0.09903292]
  [0.8366501  0.53775885 0.57724513]]

 [[0.02090764 0.82940951 0.00708279]
  [0.1000244  0.7881612  0.96582376]
  [0.43891291 0.28129097 0.04945131]]]

### 11. Create a 10x10 array with random values and find the minimum and maximum values.

#### ✅출력 예시


```
0.018360924693465508 0.9990506368595156
```

In [29]:
array = np.random.rand(10,10)
print(array.min(),array.max())

0.012412617658504543 0.9957302880914265

### 12. Create a random vector of size 30 and find the mean value.

#### ✅출력 예시


```
0.46249036320403636
```

In [31]:
array = np.random.rand(30)
print(array.mean())

0.5263190497630973

### 13. Create a 2d array with 1 on the border and 0 inside. (size: 10x10)

#### ✅출력 예시


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

In [39]:
array = np.zeros((10,10))
# 1st row & last row
array[[0,-1]] = 1
# 1st col & last col
array[:,[0,-1]] = 1
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

### 14. How to add a border (filled with 0's) around an existing array?

(hint: 인덱싱 사용)

#### ✅출력 예시


```
# before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 # after
 [[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

```

In [44]:
array = np.ones((5,5))
print('# before\n',array)
# 1st row & last row
array[[0,-1]] = 0
# 1st col & last col
array[:,[0,-1]] = 0
print('# after\n',array)

# before
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
# after
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

### 15. What is the result of the following expression?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [51]:
print(0*np.nan) # not a number(NULL)라서 뭐라 곱해도 nan
print(np.nan==np.nan) # 정의되지 않는 값 -> 비교 불가능
print(np.inf>np.nan) # 정의되지 않는 값 -> 비교 불가능
print(np.nan-np.nan) # 산술 연산에서 전파되지 않음 -> 자기 자신 반환
print(np.nan in set([np.nan])) #set membership에서는 자기 자신과 동일하다고 생각해서 True
print(0.3==3*0.1) # 이진법으로 숫자를 표현해서 0.1을 정확히 표현 못하기 때문에 3*0.1은 0.3 아님

nan
False
False
nan
True
False

### 16. Normalize a 5x5 random matrix.

(hint: (x - mean) / std)

#### ✅출력 예시


```
[[-1.4765971   0.9582795  -1.29910242  1.0250981  -0.79801651]
 [ 0.57945383 -1.28559078  0.02733238  0.99675052  1.2702088 ]
 [-0.08513084 -1.4686812  -0.78813593 -0.34559303 -1.15052328]
 [ 0.98183813 -1.41255344  0.37190169  1.05697419 -0.02668639]
 [-1.14466851  0.98911205  1.14499256  0.69454882  1.18478886]]
```

In [54]:
array = np.random.rand(5,5)
mean = array.mean()
std = array.std()
normalized_array = (array-mean)/std
print(normalized_array)

[[ 0.05599131  1.1914088  -0.75235473 -0.01143456 -0.12892781]
 [ 1.97723974 -0.80967549 -0.7160676  -0.23647378  1.68172955]
 [-0.31819589  1.419103   -0.56063176  1.69420604 -1.26407607]
 [ 0.25588726 -1.96913666  0.4090735  -0.13615313  1.12493012]
 [-0.54931981 -0.35363685 -1.41731193 -0.03488071 -0.55129255]]

### 17. Multiply a 5x3 matrix by a 3x2 matrix. (real matrix product)

#### ✅출력 예시


```
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
```

In [57]:
array1 = np.ones((5,3))
array2 = np.ones((3,2))
array3 = np.dot(array1,array2)
print(array3)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]

### 18. What are the result of the following expressions?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0)/np.array(0)) # 0/0 정의되지 않는 연산 -> numpy에서는 nan으로 반환
print(np.array(0)//np.array(0)) # 0//0 정의되지 않지만 정수 나눗셈이여서 numpy 내부에서 0으로 반환
print(np.array([np.nan]).astype(int).astype(float)) # [0.] np.nan을 정수로 변환 시도를함 근데 불가능해서 0으로 반환, 0을 float로 반환해 서 0.

nan
0
[0.]

/var/folders/94/7h5frtys3qgbp8xn922gq0t40000gn/T/ipykernel_49027/1807440613.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0)/np.array(0)) # nan cuz 0/0
/var/folders/94/7h5frtys3qgbp8xn922gq0t40000gn/T/ipykernel_49027/1807440613.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0)//np.array(0)) # 0
/var/folders/94/7h5frtys3qgbp8xn922gq0t40000gn/T/ipykernel_49027/1807440613.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float)) #

### 19. Create a 5x5 matrix with row values ranging from 0 to 4.

#### ✅ 출력 예시

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [6]:
array = np.array([np.arange(5)]*5)
print(array)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

### 20. Create a random vector of size 10 and sort it.

#### ✅출력 예시


```
[0.11443045 0.16715169 0.32515597 0.38374227 0.48327044 0.78728921
 0.80523192 0.85915686 0.96930939 0.99586525]

```

In [8]:
array = np.random.rand(10)
sorted_array = np.sort(array)
print(sorted_array)

[0.00250942 0.07883914 0.11902637 0.14142992 0.19029031 0.35363293
 0.70561968 0.81937816 0.84804299 0.86966192]

## **판다스**


### 1. Import pandas under the alias `pd`.

In [9]:
import pandas as pd

### 2. Print the version of pandas that has been imported.

In [10]:
print(pd.__version__)

2.0.3

## 3~20번 문제는 아래 데이터프레임으로 진행됩니다.

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

### 3. Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [67]:
# 문제 풀이 전 numpy 임포트
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(data,index=labels)
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 4. Display a summary of the basic information about this DataFrame and its data.  
(hint: there is a single method that can be called on the DataFrame)

In [13]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes
None

### 5. Display a summary of the basic statistics about data of this DataFrame.  
(hint: there is a single method that can be called on the DataFrame)

In [14]:
print(df.describe())

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

### 6. Return the first 3 rows of the DataFrame `df`.

In [15]:
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

### 7. Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [16]:
df[['animal','age']]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

### 8. Select the data in rows `[3, 4, 8]` **and** in columns `['animal', 'age']`.

In [19]:
new_df = df.loc[df.index[[3,4,8]],['animal','age']]
new_df

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

### 9. Select only the rows where the number of visits is greater than 3.

In [22]:
visit3_df = df[df['visits']>=3]
visit3_df

  animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no

### 10. Select the rows where the age is missing, i.e. it is `NaN`.

In [25]:
age_missing_df = df[df['age'].isna()]
age_missing_df

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

### 11. Select the rows where the animal is a cat *and* the age is less than 3.

In [27]:
cond1 = df['animal'] == 'cat'
cond2 = df['age']<3
df[cond1 & cond2]

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

### 12. Select the rows the age is between 2 and 4 (inclusive).

In [30]:
new_df = df[(df['age']>=2) & (df['age']<=4)]
new_df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

### 13. Change the age in row 'f' to 1.5.

In [32]:
df['age'].loc['f'] = 1.5
df

/var/folders/94/7h5frtys3qgbp8xn922gq0t40000gn/T/ipykernel_51040/646225410.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age'].loc['f'] = 1.5

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 14. Calculate the sum of all visits in `df` (i.e. the total number of visits).

In [33]:
visit_num = df['visits'].sum()
visit_num

19

### 15. Calculate the mean age for each different animal in `df`.

In [37]:
mean_ages = df.groupby(by='animal')['age'].mean()
mean_ages

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

### 16. Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [41]:
df['k'] = 1
df.drop(labels='k',axis=1,inplace=True)
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 17. Count the number of each type of animal in `df`.

In [44]:
animal_num = df.groupby(by='animal')['animal'].count()
print(animal_num)

animal
cat      4
dog      4
snake    2
Name: animal, dtype: int64

### 18. Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).
#### ✅출력 예시

 index |animal	| age	|visits|	priority
---|---|---|---|---
i|	dog|	7.0|	2|	no
e|	dog|	5.0|	2|	no
g|	snake|	4.5|	1|	no
j|	dog|	3.0|	1|	no
b|	cat|	3.0|	3|	yes
a|	cat|	2.5|	1|	yes
f|	cat|	1.5|	3|	no
c|	snake|	0.5|	2|	no
h|	cat|	NaN|	1|	yes
d|	dog|	NaN|	3|	yes

In [53]:
sorted_array = df.sort_values(by=['age','visits'],ascending=[False,True])
sorted_array

  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  2.0       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

### 19. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.  
(hint: `map`)

In [61]:
df['priority'] = df['priority'].map({'yes': True, 'no': False})
print(df)

  animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  2.0       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False

### 20. In the 'animal' column, change the 'snake' entries to 'python'.

In [68]:
#df['animal'] = df['animal'].map({'snake':'python'})
df['animal'] = df['animal'].replace('snake','python')
df

   animal  age  visits priority
a     cat  2.5       1      yes
b     cat  3.0       3      yes
c  python  0.5       2       no
d     dog  NaN       3      yes
e     dog  5.0       2       no
f     cat  2.0       3       no
g  python  4.5       1       no
h     cat  NaN       1      yes
i     dog  7.0       2       no
j     dog  3.0       1       no

### 21. Given a DataFrame of random numeric values:
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # this is a 5x3 DataFrame of float values
```

how do you subtract the row mean from each element in the row?

In [75]:
# 랜덤 시드 고정
np.random.seed(2025)

df = pd.DataFrame(np.random.random(size=(5, 3)))
print(df)
# to get mean of row, have to find mean of each col
row_means = df.mean(axis=1)
print(row_means)
# subtract row_mean from each element in the row
df_sub = df.sub(row_means,axis=0)
df_sub

          0         1         2
0  0.135488  0.887852  0.932606
1  0.445568  0.388236  0.257596
2  0.657368  0.492617  0.964238
3  0.800984  0.455205  0.801058
4  0.041718  0.769458  0.003171
0    0.651982
1    0.363800
2    0.704741
3    0.685749
4    0.271449
dtype: float64

          0         1         2
0 -0.516494  0.235870  0.280624
1  0.081768  0.024435 -0.106204
2 -0.047373 -0.212124  0.259497
3  0.115235 -0.230544  0.115309
4 -0.229731  0.498009 -0.268278