# **1주차 복습과제**
- 1주차 복습과제는 **넘파이/판다스 연습문제**입니다.
- 코드 작성하시고, 출력 결과까지 나오도록 실행 부탁드립니다.
  - 제출 시 파일명 본인 이름으로 변경해 주세요. ex) Week1_복습과제_OOO
- 교재에서 다루지 않은 메소드도 다수 포함되어 있지만 구글링이나 챗지피티 등을 활용해서라도 풀어주세요! 한 번씩 사용해 보면 좋을 것 같아 어려워도 문제에 포함했습니다 🤗

## **넘파이**

### 1. Import the numpy package under the name `np`.

In [ ]:
import numpy as np

### 2. Print the numpy version and the configuration.

(hint: `np.__version__`, `np.show_config`)

In [ ]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp311-cp311/bin/python
  version: '3.11'
SIMD Extensions:
  baseline:
  - SSE
  - SSE2
  - SSE3
  found:
  - SSSE3
  - SSE41
  - POPCNT
  - SSE42
  - AVX
  - F16C
  - FMA3
  - AVX2
  not found:
  - AVX512F
  - AVX512CD
  - AVX512_KNL
  - AVX512_KNM
  - AVX512_SKX
  - AVX512_CLX
  - AVX512_CNL
  - AVX512_ICL

### 3. Create a null vector of size 10.

#### ✅ 출력 예시


```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```

In [ ]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

### 4. Create a null vector of size 10 but the fifth value which is 1.

#### ✅출력 예시


```
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
```

In [ ]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

### 5. Create a vector with values ranging from 10 to 49.

#### ✅출력 예시


```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
```

In [ ]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

### 6. Reverse a vector (first element becomes last).

#### ✅출력 예시


```
[9 8 7 6 5 4 3 2 1 0]
```

In [ ]:
vector = np.arange(10)
reversed_vector = vector [::-1]
print(reversed_vector)

[9 8 7 6 5 4 3 2 1 0]

### 7. Create a 3x3 matrix with values ranging from 0 to 8.

#### ✅출력 예시


```
[[0 1 2]
 [3 4 5]
 [6 7 8]]
```

In [ ]:
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

### 8. Find indices of non-zero elements from [1,2,0,0,4,0].

#### ✅출력 예시


```
(array([0, 1, 4]),)
```

In [ ]:
array = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(array)
print(indices)

(array([0, 1, 4]),)

### 9. Create a 3x3 identity matrix.

(hint: `np.eye`)

#### ✅출력 예시


```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

### 10. Create a 3x3x3 array with random values.

#### ✅출력 예시


```
[[[0.30742852 0.26458726 0.85474383]
  [0.80234531 0.76268902 0.91286677]
  [0.8804109  0.51011378 0.82103555]]

 [[0.403753   0.83120234 0.15202655]
  [0.75782685 0.0732058  0.48148689]
  [0.2089428  0.44968622 0.88134184]]

 [[0.52251191 0.10738374 0.86279648]
  [0.26203911 0.42157754 0.68856833]
  [0.58133626 0.31059127 0.71354172]]]
```

In [ ]:
random_matrix = np.random.random((3,3,3))
print(random_matrix)

[[[0.24510029 0.86561875 0.75914276]
  [0.75440516 0.15475337 0.58573825]
  [0.0524273  0.66489177 0.41415254]]

 [[0.57385165 0.95478621 0.88189032]
  [0.75116636 0.92809022 0.2750871 ]
  [0.39034303 0.0048024  0.71048728]]

 [[0.15537527 0.50331468 0.55452886]
  [0.77734471 0.22399209 0.39281102]
  [0.27180349 0.06991001 0.11838649]]]

### 11. Create a 10x10 array with random values and find the minimum and maximum values.

#### ✅출력 예시


```
0.018360924693465508 0.9990506368595156
```

In [ ]:
random_matrix = np.random.random((10,10))
min_value = np.min(random_matrix)
max_value = np.max(random_matrix)
print(min_value, max_value)

0.002921987206050969 0.9869876978366383

### 12. Create a random vector of size 30 and find the mean value.

#### ✅출력 예시


```
0.46249036320403636
```

In [ ]:
random_vector = np.random.random(30)
mean_value = np.mean(random_vector)
print(mean_value)

0.5070789387953282

### 13. Create a 2d array with 1 on the border and 0 inside. (size: 10x10)

#### ✅출력 예시


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

In [ ]:
array = np.zeros((10,10))
array[0, : ] = 1
array[-1, :] = 1
array[: , 0] = 1
array[: , -1] = 1
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

### 14. How to add a border (filled with 0's) around an existing array?

(hint: 인덱싱 사용)

#### ✅출력 예시


```
# before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 # after
 [[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

```

In [ ]:
array = np.ones((5, 5))
print("#before")
print(array)

array[0, : ] = 0
array[-1, :] = 0
array[: , 0] = 0
array[: , -1] = 0

print("#after")
print(array)

#before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
#after
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

### 15. What is the result of the following expression?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan # 출력: nan - NaN과의 연산은 항상 NaN 반환

np.nan == np.nan # 출력: False - NaN은 자기와도 같을 수 없음

np.inf > np.nan # 출력: False - NaN은 크기 비교 불가능, 항상 False 반환

np.nan - np.nan # 출력: nan - NaN과의 연산은 항상 NaN 반환

np.nan in set([np.nan]) # 출력: True - set에서는 NaN 객체 자체를 저장, 같은 객체 있으면 True 반환

0.3 == 3 * 0.1 # 출력: False - 부동소수점 연산오차, 3*0.1 = 0.30000000000000004 이므로 0.3과 같다고 할 수 없음

False

### 16. Normalize a 5x5 random matrix.

(hint: (x - mean) / std)

#### ✅출력 예시


```
[[-1.4765971   0.9582795  -1.29910242  1.0250981  -0.79801651]
 [ 0.57945383 -1.28559078  0.02733238  0.99675052  1.2702088 ]
 [-0.08513084 -1.4686812  -0.78813593 -0.34559303 -1.15052328]
 [ 0.98183813 -1.41255344  0.37190169  1.05697419 -0.02668639]
 [-1.14466851  0.98911205  1.14499256  0.69454882  1.18478886]]
```

In [ ]:
import numpy as np

matrix = np.random.random((5, 5))

mean = np.mean(matrix)
std = np.std(matrix)

normalized_matrix = (matrix - mean) / std

print(normalized_matrix)

[[-1.4075009  -0.56546851 -1.55029491 -1.06650955  1.23923371]
 [ 1.15886698 -0.88178722  1.29220338 -1.05471564  0.82707999]
 [ 1.06040713  0.88902625  0.70218073 -0.66545651 -1.50736524]
 [ 0.39284227 -1.31261548  1.05289576 -0.72537428  0.61599907]
 [-0.53784164  1.04759786 -0.27346882  0.0212694   1.24879619]]

### 17. Multiply a 5x3 matrix by a 3x2 matrix. (real matrix product)

#### ✅출력 예시


```
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
```

In [ ]:

A = np.random.random((5, 3))

B = np.random.random((3, 2))

C = np.dot(A, B)

print(C)

[[1.37171176 0.82832127]
 [0.61809531 0.47677555]
 [0.49323089 0.36794507]
 [0.72577185 0.56370286]
 [1.10820259 0.73498038]]

### 18. What are the result of the following expressions?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
# NaN - 0으로 0을 나누는 것은 수학적으로 정의될 수 없음

np.array(0) // np.array(0)
# NaN - 정수 나눗셈 역시 0으로 0을 나누느 것은 정의되지 않음

np.array([np.nan]).astype(int).astype(float)
# [-9.22337204e+18] - NaN을 int로 변환하면 최소 정수값이 되는데 다시 float로 변환하면 int64의 최소값이 float으로 변환된 값이 된다

<ipython-input-8-26af163ff714>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-8-26af163ff714>:4: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-8-26af163ff714>:7: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

### 19. Create a 5x5 matrix with row values ranging from 0 to 4.

#### ✅ 출력 예시

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [ ]:
matrix = np.tile(np.arange(5), (5, 1))

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

### 20. Create a random vector of size 10 and sort it.

#### ✅출력 예시


```
[0.11443045 0.16715169 0.32515597 0.38374227 0.48327044 0.78728921
 0.80523192 0.85915686 0.96930939 0.99586525]

```

In [ ]:
matrix = np.random.random(10)

sorted_matrix = np.sort(matrix)

print(sorted_matrix)

[0.01146544 0.1127417  0.18637066 0.26565626 0.53473795 0.5589326
 0.56533493 0.62092877 0.78866806 0.82981248]

## **판다스**


### 1. Import pandas under the alias `pd`.

In [23]:
import pandas as pd

### 2. Print the version of pandas that has been imported.

In [34]:
print(pd.__version__)

2.2.2

## 3~20번 문제는 아래 데이터프레임으로 진행됩니다.

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

### 3. Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [25]:
# 문제 풀이 전 numpy 임포트
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 4. Display a summary of the basic information about this DataFrame and its data.  
(hint: there is a single method that can be called on the DataFrame)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 700.0+ bytes

### 5. Display a summary of the basic statistics about data of this DataFrame.  
(hint: there is a single method that can be called on the DataFrame)

In [9]:
df.describe()

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

### 6. Return the first 3 rows of the DataFrame `df`.

In [10]:
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

df.head(3)

### 7. Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [14]:
print(df[['animal', 'age']])

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

### 8. Select the data in rows `[3, 4, 8]` **and** in columns `['animal', 'age']`.

In [15]:
selected_data = df.loc[['d', 'e', 'i'], ['animal', 'age']]
print(selected_data)

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

### 9. Select only the rows where the number of visits is greater than 3.

In [16]:
visits_data = df[df['visits'] > 3]
print(visits_data)

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

### 10. Select the rows where the age is missing, i.e. it is `NaN`.

In [17]:
df_missing_age = df[df['age'].isna()]
print(df_missing_age)

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

### 11. Select the rows where the animal is a cat *and* the age is less than 3.

In [18]:
df_filtered = df[(df['animal'] == 'cat') & (df['age'] < 3)]
print(df_filtered)

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

### 12. Select the rows the age is between 2 and 4 (inclusive).

In [19]:
df_filtered = df[(df['age'] >= 2) & (df['age'] <= 4)]
print(df_filtered)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

### 13. Change the age in row 'f' to 1.5.

In [20]:
df.at['f', 'age'] = 1.5

print(df.loc['f'])

animal      cat
age         1.5
visits        3
priority     no
Name: f, dtype: object

### 14. Calculate the sum of all visits in `df` (i.e. the total number of visits).

In [21]:
total_visits = df['visits'].sum()
print(total_visits)

19

### 15. Calculate the mean age for each different animal in `df`.

In [22]:
mean_age_per_animal = df.groupby('animal')['age'].mean()
print(mean_age_per_animal)

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

### 16. Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [26]:
df.loc['k'] = ['rabbit', 2.0, 4, 'yes']
print("After adding row 'k':")
print(df)

df = df.drop('k')
print("\nAfter deleting row 'k':")
print(df)

After adding row 'k':
   animal  age  visits priority
a     cat  2.5       1      yes
b     cat  3.0       3      yes
c   snake  0.5       2       no
d     dog  NaN       3      yes
e     dog  5.0       2       no
f     cat  2.0       3       no
g   snake  4.5       1       no
h     cat  NaN       1      yes
i     dog  7.0       2       no
j     dog  3.0       1       no
k  rabbit  2.0       4      yes

After deleting row 'k':
  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 17. Count the number of each type of animal in `df`.

In [27]:
animal_counts = df['animal'].value_counts()
print(animal_counts)

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

### 18. Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).
#### ✅출력 예시

 index |animal	| age	|visits|	priority
---|---|---|---|---
i|	dog|	7.0|	2|	no
e|	dog|	5.0|	2|	no
g|	snake|	4.5|	1|	no
j|	dog|	3.0|	1|	no
b|	cat|	3.0|	3|	yes
a|	cat|	2.5|	1|	yes
f|	cat|	1.5|	3|	no
c|	snake|	0.5|	2|	no
h|	cat|	NaN|	1|	yes
d|	dog|	NaN|	3|	yes

In [28]:
df_sorted = df.sort_values(by=['age', 'visits'], ascending=[False, True])
print(df_sorted)

  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  2.0       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

### 19. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.  
(hint: `map`)

In [30]:
df['priority'] = df['priority'].map({'yes': True, 'no': False})

print(df)

  animal  age  visits priority
a    cat  2.5       1      NaN
b    cat  3.0       3      NaN
c  snake  0.5       2      NaN
d    dog  NaN       3      NaN
e    dog  5.0       2      NaN
f    cat  2.0       3      NaN
g  snake  4.5       1      NaN
h    cat  NaN       1      NaN
i    dog  7.0       2      NaN
j    dog  3.0       1      NaN

### 20. In the 'animal' column, change the 'snake' entries to 'python'.

In [31]:
df['animal'] = df['animal'].replace('snake', 'python')

print(df)

   animal  age  visits priority
a     cat  2.5       1      NaN
b     cat  3.0       3      NaN
c  python  0.5       2      NaN
d     dog  NaN       3      NaN
e     dog  5.0       2      NaN
f     cat  2.0       3      NaN
g  python  4.5       1      NaN
h     cat  NaN       1      NaN
i     dog  7.0       2      NaN
j     dog  3.0       1      NaN

In [ ]:
# 확인용 df 출력 셀
df

### 21. Given a DataFrame of random numeric values:
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # this is a 5x3 DataFrame of float values
```

how do you subtract the row mean from each element in the row?

In [32]:
# 랜덤 시드 고정
np.random.seed(2025)

df = pd.DataFrame(np.random.random(size=(5, 3)))

In [33]:
df_centered = df.sub(df.mean(axis=1), axis=0)

print(df_centered)

          0         1         2
0 -0.516494  0.235870  0.280624
1  0.081768  0.024435 -0.106204
2 -0.047373 -0.212124  0.259497
3  0.115235 -0.230544  0.115309
4 -0.229731  0.498009 -0.268278